### ISSUE TITLE
[BE] Kafka Consumer를 통한 회원 탈퇴 시 QNA 및 결제 이력 삭제 구현

### ISSUE THREAD

**Issue by jymaeng95** [dev-nbbang/backend-party#12]
## **✏️ Feature 작업**
Kafka Consumer를 통한 회원 탈퇴 시 QNA 및 결제 이력 삭제 구현

## **✅ TO-DO** 
- [x] Kafka Consumer 구현 
- [x] Kafka Producer 구현
- [x] 결제 이력, QNA에서 회원 탈퇴 구현
- [x] 파티, 파티원에서 회원 아이디로 파티 및 파티원 존재하는지 로직 구현 

## **🚨 주의사항** 
✔️ 주의 사항
