### ISSUE TITLE
[BE] Ott 플랫폼 API 개발

### ISSUE THREAD

**Issue by jymaeng95** [dev-nbbang/backend-party#6]
## **✏️ Feature 작업**
OTT 플랫폼 API 개발

## **✅ TO-DO** 
- [ ] Ott 플랫폼 서비스 리스트 전체 조회
- [ ] 특정 Ott 플랫폼 서비스 조회
- [ ] 특정 Ott 플랫폼 서비스 삭제
- [ ] 특정 Ott 플랫폼 서비스 추가
- [ ] 특정 Ott 플랫폼 서비스 수정

## **🚨 주의사항** 
✔️ 주의 사항
