### ISSUE TITLE
[BE] Party API 서비스 개발

### ISSUE THREAD

**Issue by jymaeng95** [dev-nbbang/backend-party#8]
## **✏️ Feature 작업**
 Party API 서비스 개발

## **✅ TO-DO** 
- [ ] 파티 생성
- [ ] 파티 해체 
- [ ] 일반 결제 파티 정보 수정 
- [ ] 파티 상세 조회 
- [ ] 파티 리스트 전체 조회 
- [ ] 파티 리스트 결제 유형 필터링 조회 
- [ ] OTT 계정 중복 확인
- [ ]  일반 결제 파티 탈퇴 ( 환불 X)
- [ ] 정기결제 파티 탈퇴 시 환불 정보 조회
- [ ] 파티 공지 작성
- [ ] 파티 참가 
- [ ] OTT ID/ PW 조회 
- [ ] OTT ID/PW 수정
- [ ] 파티원 초대 
- [ ] 파티원 초대 시 파티 가입 여부 판단
- [ ] 일주일 매칭 인원수

## **🚨 주의사항** 
✔️ 주의 사항
